import type { Metadata } from "next";
import { LegalPageLayout } from "@/components/legal-page-layout";
import { siteConfig } from "@/lib/site";
import { getLocale } from "@/lib/i18n/server";

export async function generateMetadata(): Promise<Metadata> { const en = (await getLocale()) === "en"; return { title: en ? "Kalkulator Komisi Shopee Privacy" : "Privasi Kalkulator Komisi Shopee", description: en ? "Privacy policy for the Kalkulator Komisi Shopee Chrome Extension." : "Kebijakan privasi khusus Chrome Extension Kalkulator Komisi Shopee.", alternates: { canonical: "/products/kalkulator-komisi-shopee/privacy" } }; }

export default async function ExtensionPrivacyPage() {
  const en = (await getLocale()) === "en";
  if (en) return <LegalPageLayout eyebrow="Kalkulator Komisi Shopee" title="Extension Privacy Policy" description="How Kalkulator Komisi Shopee uses sessions and reports to provide its core functionality.">
    <h2>1. Scope</h2><p>This policy applies specifically to the Kalkulator Komisi Shopee Chrome Extension. Grahito Labs account practices are described separately in the general Privacy Policy.</p>
    <h2>2. Shopee authentication sessions</h2><p>Shopee authentication session data is sensitive. The extension detects an authentication session already available in the browser so it can request reports selected by the user.</p><ul><li>Shopee authentication cookie values are not stored by the extension.</li><li>Shopee cookies are not sent to Grahito Labs servers.</li><li>Shopee cookies are not sold or shared with third parties.</li></ul>
    <h2>3. Report processing</h2><p>Report requests are sent directly from the user&apos;s browser to <code>affiliate.shopee.co.id</code>. Commission calculations are performed inside the extension. Grahito Labs does not receive authentication cookie values through this process.</p><p>If account synchronization is added in the future, only commission summary results may be sent after the user provides consent. This policy will be updated before that feature is released.</p>
    <h2>4. Chrome permissions</h2><p>The extension may require the following permissions according to its published manifest:</p><ul><li><strong>cookies</strong> — detect the Shopee session required by the product without storing cookie values.</li><li><strong>host permissions for relevant Shopee domains</strong> — send report requests directly to Shopee domains from the user&apos;s browser.</li><li><strong>storage</strong> — store local extension preferences, such as display choices or the most recent date range, rather than Shopee authentication cookie values.</li></ul><p><strong>TODO: MATCH THIS LIST TO THE FINAL MANIFEST BEFORE PUBLICATION.</strong></p>
    <h2>5. Data practices</h2><ul><li>No sale of data.</li><li>No behavioral advertising.</li><li>No browsing-history tracking outside product functionality.</li><li>No unverifiable security guarantee or certification claims.</li></ul>
    <h2>6. Installation identity and device limit</h2><p>To enforce a maximum of two active installations per account, the extension generates a random installation identifier and stores it in extension-local storage. Grahito Labs may store that identifier, the user-provided device name, platform type, activation time, active status, and last validation time.</p><p>The extension does not read or store MAC addresses. The installation identifier is not a hardware identity and will change if the extension is removed and reinstalled. Users can view devices in the account dashboard. To reduce repeated access transfers, a device can only be revoked after seven full days from its most recent activation.</p>
    <h2>7. Revoking access</h2><p>You can revoke a device through the account dashboard and remove Kalkulator Komisi Shopee from Chrome. After its device token is revoked, that installation will no longer pass service validation.</p>
    <h2>8. Grahito Labs account data deletion</h2><p>To request deletion of Grahito Labs account data, contact <strong>{siteConfig.supportEmail}</strong>. <strong>TODO: FINALIZE THE EMAIL AND ACCOUNT DELETION PROCESS.</strong></p>
    <h2>9. Independent product</h2><p>Kalkulator Komisi Shopee is an independent product and is not affiliated with, sponsored, endorsed, or managed by Shopee. Shopee and all related trademarks belong to their respective owners.</p>
    <h2>10. Contact</h2><p>Questions about extension privacy can be sent to <strong>{siteConfig.supportEmail}</strong>. <strong>TODO: REPLACE WITH THE FINAL SUPPORT EMAIL.</strong></p>
  </LegalPageLayout>;

  return <LegalPageLayout eyebrow="Kalkulator Komisi Shopee" title="Kebijakan Privasi Ekstensi" description="Cara Kalkulator Komisi Shopee menggunakan sesi dan laporan untuk menjalankan fungsi utamanya.">
    <h2>1. Ruang lingkup</h2><p>Kebijakan ini berlaku khusus untuk Chrome Extension Kalkulator Komisi Shopee. Kebijakan akun Grahito Labs dijelaskan terpisah dalam Kebijakan Privasi umum.</p>
    <h2>2. Sesi autentikasi Shopee</h2><p>Data sesi autentikasi Shopee bersifat sensitif. Ekstensi mendeteksi sesi autentikasi yang sudah tersedia di browser agar dapat meminta laporan yang dipilih pengguna.</p><ul><li>Nilai cookie autentikasi Shopee tidak disimpan oleh ekstensi.</li><li>Cookie Shopee tidak dikirim ke server Grahito Labs.</li><li>Cookie Shopee tidak dijual atau dibagikan kepada pihak ketiga.</li></ul>
    <h2>3. Pemrosesan laporan</h2><p>Permintaan laporan dikirim langsung dari browser pengguna ke <code>affiliate.shopee.co.id</code>. Perhitungan komisi dilakukan di dalam ekstensi. Grahito Labs tidak menerima nilai cookie autentikasi melalui proses ini.</p><p>Apabila sinkronisasi akun ditambahkan di masa depan, hanya ringkasan hasil komisi yang boleh dikirim setelah pengguna memberikan persetujuan. Kebijakan ini akan diperbarui sebelum fitur tersebut dirilis.</p>
    <h2>4. Permission Chrome</h2><p>Ekstensi dapat memerlukan permission berikut sesuai manifest versi yang diterbitkan:</p><ul><li><strong>cookies</strong> — mendeteksi keberadaan sesi Shopee yang dibutuhkan oleh fungsi produk tanpa menyimpan nilai cookie.</li><li><strong>host permissions untuk domain Shopee terkait</strong> — mengirim permintaan laporan langsung ke domain Shopee dari browser pengguna.</li><li><strong>storage</strong> — menyimpan preferensi lokal ekstensi, seperti pilihan tampilan atau rentang terakhir, bukan nilai cookie autentikasi Shopee.</li></ul><p><strong>TODO: COCOKKAN DAFTAR INI DENGAN MANIFEST FINAL SEBELUM PUBLIKASI.</strong></p>
    <h2>5. Praktik data</h2><ul><li>Tidak ada penjualan data.</li><li>Tidak ada iklan berbasis perilaku.</li><li>Tidak ada pelacakan riwayat browsing di luar fungsi produk.</li><li>Tidak ada klaim sertifikasi atau jaminan keamanan yang tidak dapat dibuktikan.</li></ul>
    <h2>6. Identitas instalasi dan batas perangkat</h2><p>Untuk menerapkan batas maksimal dua instalasi aktif per akun, ekstensi membuat pengenal instalasi acak dan menyimpannya melalui penyimpanan lokal ekstensi. Grahito Labs dapat menyimpan pengenal instalasi tersebut, nama perangkat yang diberikan pengguna, jenis platform, waktu aktivasi, status aktif, serta waktu validasi terakhir.</p><p>Ekstensi tidak membaca atau menyimpan MAC address. Pengenal instalasi bukan identitas perangkat keras dan akan berubah apabila ekstensi dihapus lalu dipasang kembali. Pengguna dapat melihat perangkat melalui dashboard akun. Untuk mengurangi pemindahan akses berulang, perangkat baru dapat dicabut setelah tujuh hari penuh sejak aktivasi terakhir.</p>
    <h2>7. Mencabut akses</h2><p>Kamu dapat mencabut perangkat melalui dashboard akun dan menghapus Kalkulator Komisi Shopee dari Chrome. Setelah token perangkat dicabut, instalasi tersebut tidak lagi lolos validasi layanan.</p>
    <h2>8. Penghapusan data akun Grahito Labs</h2><p>Untuk meminta penghapusan data akun Grahito Labs, hubungi <strong>{siteConfig.supportEmail}</strong>. <strong>TODO: FINALISASI EMAIL DAN PROSES PENGHAPUSAN AKUN.</strong></p>
    <h2>9. Produk independen</h2><p>Kalkulator Komisi Shopee adalah produk independen dan tidak berafiliasi, disponsori, disetujui, atau dikelola oleh Shopee. Shopee dan seluruh merek terkait merupakan milik pemegang hak masing-masing.</p>
    <h2>10. Kontak</h2><p>Pertanyaan mengenai privasi ekstensi dapat dikirim ke <strong>{siteConfig.supportEmail}</strong>. <strong>TODO: GANTI DENGAN EMAIL DUKUNGAN FINAL.</strong></p>
  </LegalPageLayout>;
}
